<?php
/* $Id$
 *
 * Drupal Module: Path Access
 * Restrict access to any drupal path on a per user role basis
 *
 * @author: Mike Carter <mike@ixis.co.uk>
 * @usage: ?q=admin/access/path to configure path restrictions per role.
 */

/**
 * Implementation of hook_help().
 */
function path_access_help($section) {
  switch ($section) {
    case 'admin/help#access':
      return t('blah');
    case 'admin/modules#description':
      return t('Controls user access to any path');
    case 'admin/access/path':
      return t('Each user role can be granted or denied access to any url paths. This is a crude but straight forward way to restrict groups of nodes/pages to certain users using only the paths associated with the pages. Page access is not limited to node pages only, anything can be controlled using paths.');
  }
}

function _path_access_stringquote(&$item1, $key) {
  $item1 = "'{$item1}'";
}

function path_access_init() {
  global $user;

  drupal_bootstrap(DRUPAL_BOOTSTRAP_PATH);

  $roles = $user->roles;

  // User #1 has all privileges:
  if ($user->uid == 1) {
    return 1;
  }

  array_walk($roles, '_path_access_stringquote');
  $rolenames = implode(",", $roles);
  $result = db_query("SELECT pages, visibility FROM {path_access} pa INNER JOIN {role} r ON r.rid = pa.rid WHERE r.name IN ($rolenames)");

  $visibility = 1;
  $pages = '';
  while ($role = db_fetch_object($result)) {
    $pages .= $role->pages . "\n";
    $visibility = $role->visibility AND $visibility;
  }
  $visibility = $visibility > 0 ? true : false;

  // Match path if necessary
  if ($pages) {
    $path = drupal_get_path_alias($_GET['q']);
    $regexp = '/^('. preg_replace(array('/(\r\n?|\n)/', '/\\\\\*/', '/(^|\|)\\\\<front\\\\>($|\|)/'), array('|', '.*', '\1'. variable_get('site_frontpage', 'node') .'\2'), preg_quote($pages, '/')) .')$/';
    $page_match = ($visibility xor preg_match($regexp, $path));
  }
  else {
    $page_match = TRUE;
  }

  if($page_match) {
    drupal_access_denied();
    exit;
  }

}


/**
 * Implementation of hook_menu().
 */
function path_access_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'admin/access/path/edit', 'title' => t('configure role paths'),
      'access' => user_access('administer url aliases'),
      'callback' => 'path_access_admin_role_configure',
      'type' => MENU_CALLBACK);
    $items[] = array('path' => 'admin/access/path', 'title' => t('urls'),
      'access' => user_access('administer url aliases'),
      'callback' => 'path_access_admin_roles',
      'type' => MENU_LOCAL_TASK);
  }

  return $items;
}


/**
 * Menu callback; displays the block configuration form.
 */
function path_access_admin_roles() {

  // Render the role overview.
  $result = db_query('SELECT * FROM {role} ORDER BY name');

  $header = array(t('Name'), t('Operations'));
  while ($role = db_fetch_object($result)) {
    $rows[] = array($role->name, l(t('edit'), 'admin/access/path/edit/'. $role->rid));
  }

  $output = theme('table', $header, $rows);

  print theme('page', $output);
}


/**
 * Menu callback; displays the block configuration form.
 */
function path_access_admin_role_configure($module = NULL, $delta = 0) {
  $edit = $_POST['edit'];
  $op = $_POST['op'];
  $roleid = arg(4);

  switch ($op) {
    case t('Save path access'):
      if ($edit['types']) {
        $types = implode(',', $edit['types']);
      }
      else {
        $types = '';
      }

      db_query("UPDATE {path_access} SET visibility = %d, pages = '%s' WHERE rid = %d", $edit['visibility'], $edit['pages'], $roleid);

      drupal_set_message('The path access configuration has been saved.');
      drupal_goto('admin/access/path');

    default:
      if (!$edit) {
        $edit = db_fetch_array(db_query("SELECT * FROM {path_access} pa INNER JOIN {role} r ON pa.rid = r.rid WHERE pa.rid = %d", $roleid));

        // Obtain role name for the page
        if(!$edit) {
          $rolename = db_result(db_query("SELECT name FROM role WHERE rid = %d", $roleid));
          $pid = db_next_id('path_access');
          db_query("INSERT INTO {path_access} (pid, rid, pages, visibility) VALUES (%d, %d, '', '')", $pid, $roleid);
        } else {
          $rolename = $edit['name'];
        }
      }

      drupal_set_title(t("Path access for '%role' role", array('%role' => $rolename)));

      $form['page_vis_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Page specific visibility settings'),
        '#collapsible' => FALSE,
      );
      $form['page_vis_settings']['visibility'] = array(
        '#type' => 'radios',
        '#title' => t('Allow users to view specific pages'),
        '#options' => array(t('Access every page except the listed pages.'), t('Access only the listed pages.')),
        '#default_value' => $edit['visibility'],
      );
      $form['page_vis_settings']['pages'] = array(
        '#type' => 'textarea',
        '#title' => t('Pages'),
        '#default_value' => $edit['pages'],
        '#description' => t("Enter one page per line as a path. The '*' character is a wildcard. Example paths are '<em>blog</em>' for the blog page and '<em>blog/*</em>' for every personal blog. '<em>&lt;front&gt;</em>' is the front page."),
      );
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save path access'),
      );


      return drupal_get_form('pathaccess_admin_configure', $form);
  }
}
?>