<?php

/**
 * @file
 * Restricts access to any Drupal path on a per-role basis.
 *
 * @author: Mike Carter <www.ixis.co.uk>
 * @author: CSÉCSY László <boobaa.no@spam.kybest.hu>
 * @author: Chris Burgess (@grobot) <www.giantrobot.co.nz>
 * @usage: ?q=admin/people/pathaccess to configure path restrictions for each role.
 */

/**
 * Implements hook_help().
 */
function path_access_help($path, $arg) {
  switch ($path) {
    case 'admin/people/pathaccess':
      return t('Each user role can be granted or denied access to any url paths. This is a crude but straight forward way to restrict groups of nodes/pages to certain users using only the paths associated with the pages. Page access is not limited to node pages only, anything can be controlled using paths.');
  }
}

/**
 * Implements hook_menu_alter().
 */
function path_access_menu_alter(&$items) {
  foreach ($items as $path => &$item) {
    // Default menu items don't necessarily have access arguments explicitly defined,
    // and the default access callback is user_access which requires an access argument.
    // In core, if access arguments have not been set, they are set to those of the parent
    // item in _menu_router_build. We use a similar logic here to ensure that the access
    // callback and arguments are set to those of the parent if they have not been explicitly
    // defined on the item. This ensure that chain_menu_access_chain functions correctly
    // (mrfelton).
    if (isset($item['type']) && ($item['type'] == MENU_DEFAULT_LOCAL_TASK) && !isset($item['access callback'])) {
      $parts = explode('/', $path, MENU_MAX_PARTS);
      $number_parts = count($parts);
      $parent_path = implode('/', array_slice($parts, 0, $number_parts-1));
      if (isset($items[$parent_path]) && $parent = $items[$parent_path]) {
        if (isset($parent['access callback'])) {
          $item['access callback'] = $parent['access callback'];
        }
        if (!isset($item['access arguments']) && isset($parent['access arguments'])) {
          $item['access arguments'] = $parent['access arguments'];
        }
      }
    }
    chain_menu_access_chain($item, '_path_access_check_permission');
  }
}

/**
 * Implements hook_menu().
 */
function path_access_menu() {
  $items = array();

  $items['admin/people/pathaccess/edit'] = array(
    'title' => t('configure role paths'),
    'page callback' => 'path_access_admin_role_configure',
    'access arguments' => array('administer url aliases'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/people/pathaccess'] = array(
    'title' => t('Path Access'),
    'description' => t('Define what paths a user role can access.'),
    'page callback' => 'path_access_admin_roles',
    'access arguments' => array('administer url aliases'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 30,
  );

  return $items;
}

/**
 * Access callback; patch access check.
 */
function _path_access_check_permission() {
  global $user;
  
  // User #1 has all privileges:
  if ($user->uid == 1) {
    return 1;
  }
  // This one does not work in D6 without the role_weights module, so the user's
  // last role_id will be taken into account.
  // $role = module_exists('role_weights') ? module_invoke('role_weights', 'get_highest', $user->roles) : array('name' => $user->roles);
  foreach ($user->roles as $k => $v) {
    $role = $k;
  }

  $visibility = 1;
  $pages = '';
  $result = db_query('SELECT pages, visibility FROM {path_access} WHERE rid = :role', array( ':role' => $role ));
  foreach ($result as $role) {
    $pages .= $role->pages . "\n";
    $visibility = $role->visibility && $visibility;
  }
  $visibility = ($visibility > 0) ? TRUE : FALSE;

  // Match path if necessary.
  if ($pages) {
    // The current page.
    $path = drupal_get_path_alias(check_plain($_GET['q']));
    $regexp = '/^(' . preg_replace(array('/(\r\n?|\n)/', '/\\\\\*/', '/(^|\|)\\\\<front\\\\>($|\|)/'), array('|', '.*', '\1' . variable_get('site_frontpage', 'node') . '\2'), preg_quote($pages, '/')) . ')$/';
    $page_match = ($visibility xor preg_match($regexp, $path));
  }
  else {
    $page_match = FALSE;
  }
  
  // Check that the current page is not a protected page before blocking user.
  if ($page_match && !path_access_protected_pages($path)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Menu callback; displays the path access configuration form.
 */
function path_access_admin_roles() {
  // Render the role overview.
  $result = db_query('SELECT * FROM {role} ORDER BY name');
  $table['header'] = array(t('User Role'), t('Operations'));  
  foreach ($result as $role) {
    $table['rows'][] = array($role->name, l(t('edit'), 'admin/people/pathaccess/edit/' . $role->rid));
  }
  $output = theme('table', $table);

  return $output;
}

/**
 * Menu callback; displays the configuration form.
 */
function path_access_admin_role_configure() {
  $roleid = (integer) arg(4);

  $settings = db_query('SELECT * FROM {path_access} pa INNER JOIN {role} r ON pa.rid = r.rid WHERE pa.rid = :rid', array(':rid' => $roleid))->fetchObject();

  // Obtain role name for the page if there is no existing path settings for this role id.
  if (!$settings) {
    $rolename = db_query('SELECT name FROM {role} WHERE rid = :rid', array(':rid' => $roleid))->fetchField();
    db_query("INSERT INTO {path_access} (rid, pages, visibility) VALUES (:rid, '', 0)", array(':rid' => $roleid));
  }
  else {
    $rolename = $settings->name;
  }

  drupal_set_title(t("Path access for '@role' role", array('@role' => $rolename)));

  return drupal_get_form('path_access_admin_configure_form', $settings);
}

/**
 * Define role access form.
 */
function path_access_admin_configure_form($form, &$form_state) {
  $form['page_vis_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Page specific visibility settings'),
    '#collapsible' => FALSE,
  );
  $form['page_vis_settings']['visibility'] = array(
    '#type' => 'radios',
    '#title' => t('Allow users to view specific pages'),
    '#options' => array(t('Access every page except the listed pages.'), t('Access only the listed pages.')),
    '#default_value' => ( isset($form_state['build_info']['args'][0]->visibility) ? $form_state['build_info']['args'][0]->visibility : '' ),
  );
  $form['page_vis_settings']['pages'] = array(
    '#type' => 'textarea',
    '#title' => t('Pages'),
    '#default_value' => ( isset($form_state['build_info']['args'][0]->pages) ? $form_state['build_info']['args'][0]->pages : '' ),
    '#description' => t("Enter one page per line as a path. The '*' character is a wildcard. Example paths are '<em>blog</em>' for the blog page and '<em>blog/*</em>' for every personal blog. '<em>&lt;front&gt;</em>' is the front page."),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save path access'),
  );
  $form['rid'] = array(
    '#type' => 'value', 
    '#value' => ( isset($form_state['build_info']['args'][0]->rid) ? $form_state['build_info']['args'][0]->rid : arg(4) ),
  );

  return $form;
}

/**
 * Validate role access form submission.
 */
function path_access_admin_configure_form_validate($form_id, &$form_state) {
  if ( $form_state['values']['visibility'] == 0 ) {
    // Prevent protected pages from being listed.
    $pages = explode("\n", $form_state['values']['pages']);
    foreach ( $pages as $page ) {
      if ( path_access_protected_pages($page) ) {
        form_set_error('pages', t('You cannot block access to the %protected page.', array('%protected' => $page)));
      }
    }
  }
  // else ... do we *require* that each protected page be visible?
}

/**
 * Process role access form submission
 */
function path_access_admin_configure_form_submit($form_id, &$form_state) {
  db_query("UPDATE {path_access} SET visibility = :visibility, pages = :pages WHERE rid = :rid", array(':rid' => $form_state['values']['rid'], ':visibility' => $form_state['values']['visibility'], ':pages' => $form_state['values']['pages']));

  drupal_set_message(t('The path access configuration has been saved.'));
  $form_state['redirect'] = 'admin/people/pathaccess';
}

/**
 * Protected Pages can never be restricted using path_access.
 *
 * @TODO This should be a variable_get() so it's customisable per-site.
 */
function path_access_protected_pages($page) {
  $pages = array(
    'logout',
  );
  return in_array($page, $pages);
}
