<?php
/**
 * @file
 *
 * Restricts access to any Backdrop CMS path on a per-role basis.
 */

/**
 * Implements hook_config_info().
 */
function path_access_config_info() {
  $info['path_access.settings'] = array(
    'name_key' => 'name',
    'label_key' => 'label',
    'group' => t('Path Access'),
  );
  return $info;
}

/**
 * Implements hook_preprocess_page().
 *
 * Hide the login link on logged in pages.
 * @see https://www.drupal.org/project/path_access/issues/2005136
 */
function path_access_preprocess_page(&$page) {
  $options = array('every_page' => TRUE);
  $css_path = backdrop_get_path('module', 'path_access') . '/css/path_access.css';
  backdrop_add_css($css_path, $options);
}

/**
 * Implements hook_menu_alter().
 */
function path_access_menu_alter(&$items) {
  foreach ($items as $path => &$item) {
    // Prevent the module from interferring with system callbacks.
    $item_module = $item['module'] ?? '';
    $item_type = $item['type'] ?? MENU_NORMAL_ITEM;
    if ($item_module == 'system' && $item_type == MENU_CALLBACK) {
      $check_item = $item;
      continue;
    }
    chain_menu_access_chain($items, $path, '_path_access_check_permission');
  }
}

/**
 * Implements hook_menu().
 */
function path_access_menu() {
  $items = array();
  $items['admin/config/people/path-access'] = array(
    'title' => t('Path Access'),
    'description' => t('Define what paths a user role can access.'),
    'page callback' => 'path_access_admin_roles',
    'access arguments' => array('administer permissions'),
  );
  $items['admin/config/people/path-access/%user_role'] = array(
    'title' => t('Configure Role Paths'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('path_access_admin_configure_form', 4),
    'access arguments' => array('administer permissions'),
  );
  return $items;
}

/**
 * Access callback; patch access check.
 */
function _path_access_check_permission() {
  global $user;

  // User #1 has all privileges:
  if ($user->uid == 1) {
    return TRUE;
  }

  // Get the path to check.
  $path = backdrop_get_path_alias();
  $path = backdrop_strtolower($path);

  // Count the number of roles for this user.
  $count_user_roles = count($user->roles);

  // Count the number of configured roles for this user with a setting of
  // 'allow_list'.
  $count_allow_list = 0;

  // Count the number of configured roles for this user with a setting of
  // 'deny_list'.
  $count_deny_list = 0;

  // Get a list of config files for the system roles.
  $config_prefix = 'path_access.settings';
  $config_names = config_get_names_with_prefix($config_prefix);

  // Get all the roles so we can extract the role weight to use in determining
  // how to apply the settings if a user has more than one role.
  $system_roles = user_roles(FALSE, NULL, TRUE);

  // Loop through all the user's role and retrieve the settings.
  $role_settings = array();
  foreach ($user->roles as $role) {
    // Set the role weight.
    $role_settings[$role] = array(
      'weight' => $system_roles[$role]->weight,
    );

    // Check if the config exists for that role and apply the default settings
    // if the config does not yet exist.
    $config_name = $config_prefix . '.' . $role;
    if (array_search($config_name, $config_names) === FALSE) {
      $role_settings[$role]['settings'] = array(
        'visibility_option' => 'deny_list',
        'pages' => array(),
      );
    }
    else {
      // Get the config for the role.
      $config = config($config_name);
      $role_settings[$role]['settings'] = $config->get();

      switch ($role_settings[$role]['settings']['visibility_option']) {
        case 'deny_list':
          $count_deny_list++;
          break;
        case 'allow_list':
          $count_allow_list++;
      }
    }
    // Set the role with the highest weight, which is the last in the array.
    $highest_role = $role;
  }

  // Check if all roles use 'deny_list'.
  if ($count_user_roles == $count_deny_list) {
    // If so, then just take the pages from the highest weight role, which is
    // recommended to have the most privileges.
    $pages = $role_settings[$highest_role]['settings']['pages'];
    $settings = array(
      'option' => 'deny_list',
      'pages' => $pages,
    );
  }
  // If not, check if all roles use 'allow_list'.
  elseif ($count_user_roles == $count_allow_list) {
    // If so, add together all the allowed pages.
    $pages = array();
    foreach ($role_settings as $role_setting) {
      $pages = array_merge($pages, $role_setting['settings']['pages']);
      $pages = array_unique($pages);
    }
    $settings = array(
      'option' => 'allow_list',
      'pages' => $pages,
    );
  }
  else {
    // If neither of the above, are true then collect all the allow pages and
    // find the highest 'deny_list' role.
    $allow_pages = array();
    foreach ($role_settings as $role_name => $role_setting) {
      if ($role_setting['settings']['visibility_option'] == 'allow_list') {
        // Add the pages to a list of allowed pages.
        $allow_pages = array_merge($allow_pages, $role_setting['settings']['pages']);
      }
      else {
        // Set the highest deny_list role.
        $highest_deny_role = $role_name;
      }
    }
    // For pages, start with the list to deny in the highest deny role.
    $pages = $role_settings[$highest_deny_role]['settings']['pages'];

    // Remove any allow_pages from the list of deny_pages.
    $pages = array_diff($pages, $allow_pages);
    $settings = array(
      'option' => 'deny_list',
      'pages' => $pages,
    );
  }

  // Check if the path matches any pages.
  $pages = $settings['pages'];
  if (!empty($pages)) {
    $pattern = implode(PHP_EOL, $pages);
    $check_path = backdrop_match_path($path, $pattern);
  }
  else {
    $check_path = FALSE;
  }

  // Determine the result based on the option and the result of checking the
  // path.
  $result = ($settings['option'] == 'deny_list') ? !$check_path : $check_path;

  // Check protected pages.
  if (path_access_protected_pages($path)) {
    $result = TRUE;
  }

  return $result;
}

/**
 * Menu callback; displays the path access configuration form.
 */
function path_access_admin_roles() {

  // Define explanatory text to explain how Path Access works if a user has
  // more than one role.
  $help = '<p>' . t("At it's simplest, Path Access allows you to deny access to particular paths for a role or allow a role to only access certain paths. However, in Backdrop a user can have more than one role and in those cases permissions are added together. Path Access attempts to reflect this in how configuration is interpreted when a user has more than one role:") . '</p>';
  $help_items = array();
  $help_items[] = t("<strong>All user's roles set to 'Deny list':</strong> The paths from the highest weight role a user has are denied and all other paths are allowed.");
  $help_items[] = t("<strong>All user's roles set to 'Allow list':</strong> The allow paths from all roles the user has are combined, with any duplicates removed.");
  $help_items[] = t("<strong>User's roles are mix of 'Allow list' and 'Deny list':</strong> The path list from the highest weight role set to 'Deny list' is used as the base and all roles with 'Allow list' are examined to see if the paths cancel out any of the 'Deny list' paths.");
  $help .= theme('item_list', array('items' => $help_items));
  $help .= '<p>' . t("User roles are ordered on the <a href='/admin/config/people/roles'>Roles page</a> and Backdrop recommends that roles are ordered from least permissive (lowest weight) to most permissive (highest weight) and the module uses this weight ordering to inform the logic above. That order is reflected in the table below.") . '</p>';

  $page = array();
  $page['help'] = array(
    '#type' => 'details',
    '#summary' => t('How Path Access works'),
    '#details' => $help,
    '#open' => TRUE,
    '#attributes' => array(
      'class' => array('description'),
    ),
    '#weight' => -1,
  );

  // Define the table of roles with a link to configure each role.
  // Get all roles.
  $roles = user_roles(FALSE, NULL, TRUE);

  // Define the header.
  $header = array(t('Role Name'), t('Description'), t('Operations'));
  // Define the rows for each role.
  foreach ($roles as $role) {
    $rows[] = array(
      $role->label,
      $role->description,
      l(t('Configure'), 'admin/config/people/path-access/' . $role->name, array(
        'query' => array(
          'destination' => 'admin/config/people/path-access',
        ),
      )),
    );
  }
  $page['table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );

  return $page;
}

/**
 * Define role access form.
 */
function path_access_admin_configure_form($form, &$form_state, $role) {

  // Set the page title.
  backdrop_set_title(t("Path access for '@role' role", array('@role' => $role->label)));
  // Get the config for the selected role.
  $config_name = 'path_access.settings.' . $role->name;
  $config = config($config_name);

  $form['#config'] = $config_name;

  // Set the name_key and label_key values.
  $form['name'] = array(
    '#type' => 'value',
    '#value' => $role->name,
  );
  $form['label'] = array(
    '#type' => 'value',
    '#value' => $role->label,
  );

  // Set the visibility option for this role.
  $form['visibility_option'] = array(
    '#type' => 'radios',
    '#title' => t('Allow users to view specific pages'),
    '#options' => array(
      'deny_list' => t('Deny list'),
      'allow_list' => t('Allow list'),
    ),
    '#default_value' => $config->get('visibility_option') ?? 'deny_list',
  );

  // Moved the original option names to a description.
  $form['visibility_option']['deny_list']['#description'] = t('Access every page except the listed pages.');
  $form['visibility_option']['allow_list']['#description'] = t('Access only the listed pages.');

  // Provide a text area to enter paths and path patterns.
  $form['pages'] = array(
    '#type' => 'textarea',
    '#title' => t('Pages'),
    '#default_value' => implode(PHP_EOL, $config->get('pages') ?? []),
    '#description' => t("Enter one page per line as a path. The '*' character is a wildcard. Example paths are '<em>blog</em>' for the blog page and '<em>blog/*</em>' for every personal blog. '<em>&lt;front&gt;</em>' is the front page."),
  );

  // Add an additional submit handler to convert the contents of the pages
  // text area to an array before saving to configuration.
  $form['#submit'][] = 'path_access_pages_array';

  // Use the default Backdrop system settings form handler.
  $form = system_settings_form($form);

  // Add an additional submit handler after saving configuration to clear the
  // menu cache. Uses the Backdrop function.
  $form['#submit'][] = 'menu_cache_clear_all';

  // Change the submit button name.
  $form['actions']['submit']['#value'] = t('Save Path Access Role Configuration');

  // Add a cancel button.
  $form['actions']['cancel'] = array(
    '#markup' => l(t('Cancel'), 'admin/config/people/path-access'),
  );
  return $form;
}

/**
 * Convert the text box contents of pages to an array.
 */
function path_access_pages_array($form, &$form_state) {
  $form_state['values']['pages'] = preg_split("/\r\n|\n|\r/", $form_state['values']['pages']);
}

/**
 * Validate role access form submission.
 */
function path_access_admin_configure_form_validate($form, &$form_state) {
  if ( $form_state['values']['visibility_option'] == 'deny_list' ) {
    // Prevent protected pages from being listed.
    $pages = explode("\n", $form_state['values']['pages']);
    foreach ($pages as $page) {
      if (path_access_protected_pages($page)) {
        form_set_error('pages', t('You cannot block access to the %protected page.', array('%protected' => $page)));
      }
    }
  }
}

/**
 * Protected Pages can never be restricted using path_access.
 */
function path_access_protected_pages($page) {
  $pages = array(
    'user/logout',
  );
  return in_array($page, $pages);
}
